### ISSUE TITLE
Doesn't work with webpack

### ISSUE THREAD

**Issue by amannn** [davidchin/react-input-range#1]
Thanks a lot for the great component! Looks like the best of the available range sliders!

However, I'm having troubles to use this with webpack.

It throws the following error on line 480:
```
Uncaught TypeError: Cannot read property 'initializeTouchEvents' of undefined
```

Looks like React couldn't be imported.

Am I doing something wrong?

**Comment by davidchin** [comment]
Thanks @amannn! Hopefully I'll have time to look at your issues today :)

**Comment by amannn** [comment]
If you could help me with the setup in #5 I'd really like to contribute :).

**Comment by davidchin** [comment]
I updated few things regarding the module export so it should work now. :)
