### ISSUE TITLE
Integrating react input range with react redux form

### ISSUE THREAD

**Issue by kkashou** [davidchin/react-input-range#103]
Hello,

I am using react redux form to and integrating the react input range into it. 

This is my current set up:

```Javascript
<Field model='user.range' id='user.range' className='form__row' mapProps={{onUpdate: props => props.changeAction}}>
                        <InputRange
                            maxValue={100}
                            minValue={0}
value={{min: 5, max: 30}}
                        />
                    </Field>
```

But the error I am getting from my console log is this:

```
Warning: Failed prop type: The prop `onChange` is marked as required in `InputRange`, but its value is `undefined`.
```

What could I be missing? 

Thanks

**Comment by davidchin** [comment]
So `onChange` is a required prop. Since you've closed this issue, I assume you're able to get around this issue? How did you end up doing it?

**Comment by kkashou** [comment]
I actually couldn't get it to work because I was trying to pass in the onChange to the mapProps but it still wasn't recognizing it.
