### ISSUE TITLE
eslint config

### ISSUE THREAD

**Issue by ganmor** [davidchin/react-input-range#12]
Are you willing to accept dropping this eslint rule ?
```
  quotes:
    - 2
    - single
```

I'am developing on window and git automatically checkout with crlf .

**Comment by davidchin** [comment]
Not 100% sure if this rule is related to your issue :|

**Comment by ganmor** [comment]
Rereading the post it seems that I was very tired..
The rule I was talking about is the following
```
linebreak-style:
    - 2
    - unix
```

On a fresh checkout, when I start working on the project eslint is complaining about this rule.
It seems that I can configure git to force Unix line endings but I wanted to check if this was really a requirement for you.

Anyway I wanted to contribute and add the possibility to pass a style config object instead of importing and tweaking the css files.

I ended up using the current version and using css, let me know if you willing to accept such an addition.

**Comment by davidchin** [comment]
Sure. I've removed the ESLint rule and added a `.gitattributes` file to normalize new line ending :)
