### ISSUE TITLE
Ref undefined

### ISSUE THREAD

**Issue by nnnnathann** [davidchin/react-input-range#17]
Hello there,

Nice library you have here, thank you for your time.

I'm having a problem with the refs not sticking for whatever reason.  when the component tries to obtain the owner document I get this error:

`Cannot read property 'ownerDocument' of undefined`

This occurs in both the `InputRange.js` and `Slider.js` files in the function `getDocument`.

Basically, the `refs` key of the passed component instance is an empty object.

Any ideas?

Thanks again

**Comment by davidchin** [comment]
Which version of react are you using?

**Comment by nnnnathann** [comment]
Apologies, forgot to close this issue, it has mysteriously gone away.

However, I was on `^0.14.7` if you are still curious.

Feel free to close if you like.
