### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by vanminhquangtri** [davidchin/react-input-range#186]
Hello. I got this problem with Chrome browser on small/medium viewport (mobile/tablet). It is perfect with large viewport or with other browser. The problem happens when I start drag/click the edge points (start and end point). Already try adding CSS touch-action:none to .input-range__slider but it not works. Appreciate with any help. Thank you so much.

**Comment by alexandrekumagae** [comment]
Hi, I am having the same problem!

**Comment by vanminhquangtri** [comment]
The only solution I found for this problem is to use another library

**Comment by alexandrekumagae** [comment]
I found this one, and It is a great lib: https://github.com/tajo/react-range#readme
