### ISSUE TITLE
Configurable classNames

### ISSUE THREAD

**Issue by amannn** [davidchin/react-input-range#2]
Would it be possible to have the classNames be configurable through props?

**Comment by davidchin** [comment]
4559083577c313b558d950cb60c4f57869fce748 should allow you to set up your own class names if you wish to style the component differently. https://github.com/davidchin/react-input-range/blob/master/src/InputRange/defaultClassNames.js should give you the keys to configure each sub-component.

**Comment by infacq** [comment]
is there anyway I can use `react-themable`
