### ISSUE TITLE
component in the onChange

### ISSUE THREAD

**Issue by benzen** [davidchin/react-input-range#20]
Hi

I'm wondering why you decided to put the react component on the first argument of the onChange callback.

It seams odd to me but I'm sure you've got a good reason for this:
https://github.com/davidchin/react-input-range/blob/master/src/InputRange/InputRange.js#L338-L341

**Comment by davidchin** [comment]
I originally thought it might be a good idea to pass a reference so that multiple slider components could use the same callback (inside the callback, you can check the ref). But now, I think you're right... it seems a little bit odd. :neutral_face: I think I'll probably change it.

**Comment by davidchin** [comment]
The API has changed in `^1.0.0`. `onChange` callback no longer passes the component. :)
