### ISSUE TITLE
Formating label

### ISSUE THREAD

**Issue by matejstrasek** [davidchin/react-input-range#26]
Is there a way to custom format the way currently selected value is shown?

**Comment by brennj55** [comment]
Made a [pull request](https://github.com/davidchin/react-input-range/pull/28) for this functionality. :-)

**Comment by matthewlynch** [comment]
Hi @matejstrase,

Not sure if this will help you in your specific scenario but you could try and style the ::before/::after pseudo-elements. It got me around my issue as I'm not trying to do anything too clever.

e.g:
```css
.InputRange-labelContainer::after {
    content: 'GB';
}
```

![screen shot 2016-05-02 at 10 31 56](https://cloud.githubusercontent.com/assets/3437234/14951548/af32bef2-1051-11e6-95f0-e92c3fd16283.png)

**Comment by galpratama** [comment]
Is there any update about this?

**Comment by davidchin** [comment]
I recently published a [release](https://github.com/davidchin/react-input-range/releases/tag/v0.9.0) to address this issue.

So now you can do something like this

```{js}
<InputRange
  labelSuffix="GB"
  value={this.state.value}
  onChange={this.handleValueChange}
/>
```

or pass a function to `formatLabel` if you want more flexibility. Thanks @brennj55 for your original PR!
