### ISSUE TITLE
I am not allowed to npm install react-input-range@0.7.0 with react 15.0.1

### ISSUE THREAD

**Issue by ericvillemure** [davidchin/react-input-range#29]
Running 

`npm install react-input-range@0.7.0`

I get the following error:

npm WARN peerDependencies The peer dependency react@^0.14.0 included from react-input-range will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-input-range@0.7.0"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-input-range@0.7.0 wants react@^0.14.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Eric\meteorProj\test\npm-debug.log

Thanks

**Comment by davidchin** [comment]
Should be fixed now. I changed the peer dependency to be `^0.14.0 || ^15.0.0`

**Comment by ericvillemure** [comment]
Thanks
