### ISSUE TITLE
Hidden inputs never worked

### ISSUE THREAD

**Issue by DominicTobias** [davidchin/react-input-range#40]
Hey, I don't actually need this feature but it looks like the hidden inputs feature never worked since `renderHiddenInputs` just returns an empty array. You could fix it by doing something like:

``` js
function renderHiddenInputs(rangeSlider) {
  const keys = getKeys(rangeSlider);

  return keys.map((key) => {
    const name = rangeSlider.isMultiValue ?
      `${rangeSlider.props.name}${captialize(key)}` : rangeSlider.props.name;
    return <input key={key} type="hidden" name={name} />;
  });
}
```

And perhaps only render if name is passed:

``` js
{this.props.name && renderHiddenInputs(this)}
```

Otherwise you would get `undefinedMax` and `undefinedMin`

**Comment by davidchin** [comment]
Thanks for raising this issue. `v1.0.2` should fix this issue. It'll render `name` attribute accordingly. :)
