### ISSUE TITLE
just curious: why no <input type="range"> ?

### ISSUE THREAD

**Issue by christianhaller** [davidchin/react-input-range#49]
Hi David,
your component is pretty cool.
I'm new to react and wondering, why you don't use the native input element?
For a better styling?

**Comment by prasanna1211** [comment]
@christianhaller Yes styling is difficult with native input elements. Even for styling selectbox we have restrictions. We generally bind it with a <label> tag and hide selectbox and style label tag with content. Similarly in this library div's are being targeted for the same.

**Comment by christianhaller** [comment]
thanks for your answer @prasanna1211
