### ISSUE TITLE
change href value of slider to "javascript:void(0)"

### ISSUE THREAD

**Issue by Benjaki2** [davidchin/react-input-range#51]
[Code](https://github.com/davidchin/react-input-range/blob/master/src/InputRange/Slider.js#L170)

replace '#' with "javascript:void(0)" to remove unwanted link properties

trivial.

**Comment by danmo** [comment]
this is needed

**Comment by danmo** [comment]
right now on handle click, sometimes it navigates away

**Comment by davidchin** [comment]
`v1.0.2` should fix this issue. It no longer uses `<a>` for the slider. There are also some API changes, so you'll need to update accordingly if you're still using `v0.x` (please refer to the readme and the changelog). Let me know if there's any issue. :)
