### ISSUE TITLE
Moving text jumbled on iPad

### ISSUE THREAD

**Issue by deivers** [davidchin/react-input-range#52]
When I view the widget from Safari on iPad, the moving text is often jumbled.  See the screenshot.

![react-input-range](https://cloud.githubusercontent.com/assets/51914/20973411/8760ff12-bc66-11e6-9ef7-35946e6cfcc2.png)

**Comment by lxm7** [comment]
Can confirm, I too am seeing this. Is there a way throttle either rendering or eventListening for this component?

**Comment by AreWeThereYeti** [comment]
+ 1. Im seeing this in safari for mac as well.

**Comment by pigoz** [comment]
Using the following workaround fixes the problem (it's a bug in Quartz)

````
.input-range__label {
  -webkit-transform: translateZ(0);
}
```

See http://stackoverflow.com/questions/17575624/how-can-i-avoid-animation-artifacts-on-my-touch-draggable-border-radius-element for more info

**Comment by davidchin** [comment]
`v1.0.2` should fix this issue. There are also some API changes, so you'll need to update accordingly if you're still using `v0.x` (please refer to the readme and the changelog). Let me know if there's any issue. :)
