### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of undefined when using with redux-form

### ISSUE THREAD

**Issue by stralsi** [davidchin/react-input-range#56]
In a basic `create-redux-app` setup, I have the following code: 
```javascript
import 'react-input-range/dist/react-input-range.css'
import React from 'react';
import ReactDOM from 'react-dom';
import InputRange from 'react-input-range';
import { createStore, combineReducers } from 'redux';
import { Provider } from 'react-redux';
import { reducer as formReducer, reduxForm, Field } from 'redux-form';

const rootReducer = combineReducers({
  form: formReducer
});

const store = createStore(rootReducer);

const App = (props) => {
  return (
    <form onSubmit={props.handleSubmit}>
      <Field
        name="foo"
        maxValue={20}
        minValue={0}
        component={({input: {onChange, ...inputParams}, ...params})=>(
    <InputRange
      {...inputParams}
      {...params}
      onChange={(control, values) => onChange(values)}
      />
          )}
      />
    </form>
  );
};

const AppForm = reduxForm({
  form: 'test',
  initialValues: {
    foo: {
      min: 2,
      max: 10
    }
  },
  onSubmit: (values) => console.log("SUBMIT!", values)
})(App);

ReactDOM.render(
  <Provider store={store}><AppForm /></Provider>,
  document.getElementById('root')
);
```
The initial rendering is ok, but **if you drag** the InputRange a bit, it throws the following error: 

> Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
    at getDocument (Slider.js:38)
    at Slider.handleMouseUp (Slider.js:126)
> Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
    at getDocument (InputRange.js:117)
    at InputRange.handleMouseUp (InputRange.js:613)

Here's a GitHub repo where the error happens: https://github.com/stralsi/react-input-range-error

**Comment by stralsi** [comment]
I found a workaround!
I noticed that if I don't render the `InputRange` inline, but instead put it in a function outside `App`, it keeps the instance and it works as expected. 

Here is the code above modified so that everything works fine: 
```javascript
import 'react-input-range/dist/react-input-range.css'
import React from 'react';
import ReactDOM from 'react-dom';
import InputRange from 'react-input-range';
import { createStore, combineReducers } from 'redux';
import { Provider } from 'react-redux';
import { reducer as formReducer, reduxForm, Field } from 'redux-form';

const rootReducer = combineReducers({
  form: formReducer
});

const store = createStore(rootReducer);

const renderInputRange = ({input: {onChange, ...inputParams}, ...params})=>(
  <InputRange
    {...inputParams}
    {...params}
    onChange={(control, values) => onChange(values)}
  />
)

const App = (props) => {
  return (
    <form onSubmit={props.handleSubmit}>
      <Field
        name="foo"
        maxValue={20}
        minValue={0}
        component={renderInputRange}
      />
    </form>
  );
};

const AppForm = reduxForm({
  form: 'test',
  initialValues: {
    foo: {
      min: 2,
      max: 10
    }
  },
  onSubmit: (values) => console.log("SUBMIT!", values)
})(App);

ReactDOM.render(
  <Provider store={store}><AppForm /></Provider>,
  document.getElementById('root')
);
```
I noticed that you removed the `ownerDocument`, I haven't updated yet, the workaround works with the older version.

**Comment by davidchin** [comment]
Nice, thanks for letting me know!

**Comment by stralsi** [comment]
I'm closing this, my _'workaround'_ is actually the recommended way to declare `redux-form` stateless function components it's my fault for not reading the documentation properly.

> You must define the stateless function outside of your render() method, or else it will be recreated on every render and will force the Field to rerender because its component prop will be different. If you are defining your stateless function inside of render(), it will not only be slower, but your input will lose focus whenever the entire form component rerenders.
http://redux-form.com/6.5.0/docs/api/Field.md/#usage

Also, here's a fun bit of history of this issue: https://github.com/erikras/redux-form/issues/961

**Comment by ifndefdeadmau5** [comment]
Saved my day
