### ISSUE TITLE
Binding timing

### ISSUE THREAD

**Issue by jgwconsulting** [davidchin/react-input-range#6]
I was wondering if the initializeTouchEvents and autobind should happen in componentDidMount rather than the constructor? Seems to work anyway under normal circumstances but I ran it with the hot loader and it exploded with:

Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains render method but is not mounted in the DOM

**Comment by davidchin** [comment]
Hi @jgwconsulting I'm unable to replicate this issue. I made some changes and updated the README recently. Perhaps the latest update might help?
