### ISSUE TITLE
Not working for project using react 0.14

### ISSUE THREAD

**Issue by garj** [davidchin/react-input-range#7]
npm install react-input-range --save
npm WARN peerDependencies The peer dependency react@^0.13.3 included from react-input-range will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "react-input-range" "--save"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!

**Comment by davidchin** [comment]
Yep thanks, I'll look into upgrading it.

**Comment by davidchin** [comment]
Hey @garj, just released a new version [v0.5.0](https://github.com/davidchin/react-input-range/releases/tag/v0.5.0) which would work with ^0.14.0, plus other changes.
