### ISSUE TITLE
Necessary polyfills?

### ISSUE THREAD

**Issue by amannn** [davidchin/react-input-range#8]
Could you tell me which polyfills this component depends on?

I'm using it in a environment, where I can't afford including the complete Babel polyfill. I'd like to include only the polyfills that are necessary.

When I use `require('core-js/fn/symbol');`, I get the following error in IE11:
```
Object doesn't support property or method 'Symbol(Symbol.iterator)_6.dcz7vm7xaw5'
```

I also tried another `Symbol` polyfill with `require('es6-symbol/implement');`. IE11 says:
```
Object expected
```

Are there other polyfill dependencies apart from `Symbol`?

I'd need to get the component working in IE10 and IE11. I'm using version 0.3.2 of the component, as I still have to use React 0.13.3. I've also uploaded a repo demonstrating the issue [here](https://github.com/amannn/react-input-range-issue).

**Comment by davidchin** [comment]
I had a quick look, it seems like you need require these modules to run :)

```{js}
require('core-js/es6/object');
require('core-js/es6/map');
```

**Comment by amannn** [comment]
Works great, thanks!

**Comment by Andreyco** [comment]
add this to the list
```
import 'core-js/es6/weak-map';
```

**Comment by binarykitchen** [comment]
It is documented somewhere what the prerequisites are for each es6 module?

**Comment by wub** [comment]
If it's still not working for you guys, try changing `for (let foo in bar)` to `for (let foo in Array.from(bar))` (make sure you polyfill `Array.from`)
