### ISSUE TITLE
Import default css is not working

### ISSUE THREAD

**Issue by dankonino** [davidchin/react-input-range#99]
Hi guys I'm trying to import ` import 'react-input-range/lib/css/index.css'` as you mention in readme.
Default style is not displayed at all. Is there something I can do about it or I should now please? 
Thanks Mat

**Comment by jameskraus** [comment]
You might want to post an example repo to allow others to reproduce the issue. Otherwise, this is difficult to debug.

**Comment by Aldian1** [comment]
When using scss you can use @import "../../../node_modules/react-input-range/lib/css/index.css";

**Comment by amelzer** [comment]
Had the same issue using webpack and css modules. If that is your setup, make sure you don't preprocess css in node_modules

**Comment by dankonino** [comment]
Sorry guys, I was busy so much recently. I think it would just go now. I had different problem with me `easy` installing every npms to root directory instead of `app/client` so my local env was broken all the time. nothing new worked xD It works now :)

**Comment by smakosh** [comment]
It doesn't seem to work using Next js by placing the import on `_app.js`
